### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sterbini** [xsuite/xmask#3]
- [ ] Test on machine before bb (voltage, crab, orbit, tune, chroma, coupling)
- [ ]  Transform bb test script into unit test
- [ ]  Implement lumi leveling
- [ ] Move to yaml parameter still
- [ ] Define interface (script vs functions)
- [ ]  Add custom coupling
- [ ] Release LHC errors
For later:
- Import filling scheme
